eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weijiayou/test
          searchPaths: SpringCloud/configs
  application:
    name: config-server

server:
  port: 8888
